gin:
  listen: :9487
  wsListen: :9443
  mode: debug
  trustedProxies: ["127.0.0.1","172.17.0.0/16"]

mysql:
  dbs:
    - name: main
      dsn: {{MYSQL_DSN}}
      maxOpenConn: 100
      maxIdleConn: 10
      conMaxLifeTimeSeconds: 3600
    - name: read
      dsn: {{MYSQL_DSN}}
      maxOpenConn: 100
      maxIdleConn: 10
      conMaxLifeTimeSeconds: 3600
    - name: snapshot
      dsn: {{MYSQL_SNAPSHOT_DSN}}  
      maxOpenConn: 100
      maxIdleConn: 10
      conMaxLifeTimeSeconds: 3600
  rowLimit: 3000
server:
  env: prod

redis:
  addr: {{REDIS_ADDR}}
  db: 0
  pwd: {{REDIS_PASSWORD}}
  ssl: true
  maxConn: 100
  tlsVersion: "TLS 1.2"
system:
  brandName: eUSD Card
  cdnDomain: https://www.eusd.com
  s3ImgDomain: https://back.eusd.com/s3
  uploadPath: ./files

  # MAILGUN, SENDGRID
  mailChannel: MAILGUN

  mailKey: {{SYSTEM_MAIL_KEY}}
  sendMail: {{SYSTEM_SEND_MAIL}}
  mailGunMailKey: {{SYSTEM_MAIL_MAILGUN_KEY}}
  mailGunSendMail: {{SYSTEM_SEND_MAIL_MAILGUN}}
  mailGunDomain: {{SYSTEM_SEND_MAIL_DOMAIN}}
  mailGunApiBase: {{SYSTEM_SEND_MAIL_API_BASE}}
  mailGunWebhookSigningKey: {{SYSTEM_MAILGUN_SIGNING_KEY}}
  mailGunApplyCardDomain: prod.eusdmail.com

  lockMicroseconds: 100000000 #usec
  lockPollingMicroseconds: 5000 #usec
  lockWaitMicroseconds: 8000000 #usec
  redisDaoLockMicroseconds: 1000 #usec
  saltLength: 8
  rateUrl: https://bitop.com/api/home/currency/rates
  rateUrl2: https://api.binance.com/api/v3/ticker/price
  verifyServer: http://keyserver:9488/
  hashUrl: web/getHash
  verifyUrl: web/isVerify
  l2CacheExpireSeconds: 600
  redisPopTimeoutMilliseconds: 1000 #msec
  nodeSize: 2
  ratePrecision: 8
  promotionLink : https://api2.branch.io/v1/url
  promotionLinkKey : key_live_erh7a0pArpb5LfHYUiIMNpnlqqgqDPwk
  httpTimeout: 30 #sec
  workerPoolSize: 1024
  spinlockAttempts: 10
  defaultGoroutineTimeoutMilliseconds: 5000
  dbTimezoneOffset: 0
  exportLimit: 5

coinsdo:
  apiKey: {{COINSDO_API_KEY}}
  targetDeviceUuid: B30E87A5-0190-4F9A-94FD-E57DD0F18898
  secretKey: {{COINSDO_SECRET_KEY}}
  url: https://open.coinsdo.com/coinsdo/open
  getAddressUrl: /v1/addressGet
  withdrawUrl: /v1/withdraw
  deviceInfoUrl: /v1/deviceDetail
  maxLimit: 100
  submitAccount: api
  withdrawDeviceId: 5173E8B9-08DF-49FA-BBA9-6126CE7AC8EA # 這個是提幣錢包的UUID
  coinsendPrivateKey: {{COINSEND_PRIVATE_KEY}}
  reviewUuid: E20FD370-6D32-41B8-BCD7-E0422CEB01B1
  reviewDevice: auto
  withdrawAutoLevel: 2 # 0: 不自動 1: 自動通過一審 2: 自動通過二審
  associatedMainnet: |
    [[2, 10, 11, 12, 14]]

auth:
  expireTime: 98 #hr
  loginDataExpireHours: 196 #hr
  adminExpireHours: 98 #hr
  adminLoginDataExpireHours: 196 #hr
  pinUnlockMaxAttempts: 5
notify:
  otpExpireTime: 10 #min
  callbackIntervalMilliseconds: 100 #ms
  callbackTimeoutSeconds: 10 #s
  callbackTaskTimeoutSeconds: 10 #s
quote:
  expireSeconds: 9000 #sec
card:
  expireSeconds: 900 #sec
  confirmLockSeconds: 60 #sec
  reactivateAfterMinutes: 30 #min
  reactivateWaitSeconds: 30 #sec
passkey:
  displayName: 'eusd'
  domain: 'www.eusd.com'
  sites: ['https://www.eusd.com','android:apk-key-hash:3zay_3_unhc8_XFhW35m2uyUPsTj9PueeVrKZkLxr4E','android:apk-key-hash:smgJCL9loup1xumVBNERFGvuFLrmuajgrm8LF6lrf3k','android:apk-key-hash:77tFGJNt8Q2rFURKhPfzxG3E8dzdh05OFz_3O8-Vob4','android:apk-key-hash:YpSZcZN7ZqAjIiLx3sq25MKV9oeJdevc8KsKM4rJ6R4','android:apk-key-hash:9stMJE8YwfdGpqlMYFkROntlvIWt4f2og1lFLOqXnE0']
  encryptKey: '9EAWZ4xlUwMNVKs6SoFbVF2BkxXb/pLnBsyHt4bLyDw='

reap:
  baseUrl: https://prod.api.caas.reap.global/
  apiKey: {{REAP_API_KEY}}
  privateKey: {{REAP_PRIVATE_KEY}}
  publicKey: {{REAP_PUBLIC_KEY}}
  authorizationLockSeconds: 600 #sec
  authorizationAdviceLockWaitMicroseconds: 600000000 #usec
  threedsNotificationCacheSeconds: 600 #sec
  threedsNotificationTimeoutSeconds: 300 #sec
  merchantPayTimeoutMilliseconds: 800 #msec
  merchantPayWaitMilliseconds: 3000 #msec
  merchantPayTxNotifyAttempt: 5
  merchantPayTxNotifySeconds: 10 #sec
  merchantCardStatusAttempt: 3
  merchantCardStatusSeconds: 10 #sec
  merchantForward3dsAttempt: 3
  merchantForward3dsSeconds: 10 #sec
  merchantWalletOTPAttempt: 3
  merchantWalletOTPSeconds: 10 #sec
  signatureExpireSeconds: 3 #sec
  merchantPrivateKey: {{REAP_MERCHANT_PRIVATE_KEY}} 
  merchantPublicKey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDOWp0WmRWcmV2dXVXNi92ckJHbSs4NXFjWAo5ekdna0U5aFNsVVR5d3M0eEFIdGJlL0J2MkYxR2tjcEcxU0V0ellOQnVUTFJMTzBXTm9OY3pkWlJXS3RzZUowCjJZM2RYamJ0OEQ1Uk92Sm1COGk4L1lHQWo2emIwaHNoUEExTVVibHozNEVZRE1icG5oQjgxM1cyaVZ2eTJ5bE8KS2V0eUxrZjVHZzBmOTlkWmJ3SURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
  autoTopUpMinGap: 1
  autoThreedsAnswerDelayMilliseconds: 3000
  autoThreedsAnswerAttempt: 3
  autoThreedsTaskLockMilliSeconds: 100


coinface:
  host: https://liveness-check.coinsdo.com
  secretKey: {{COINFACE_SECRET_KEY}}
  # syncUrl客户端返回的地址 TODO 换成前端deeplink
  syncUrl: https://app.eusd.com/#/home?kyc=2
  asyncUrl: https://open.eusd.com/api/web/coinface/async
  kycOkUrl: https://app.eusd.com/#/kycOk
  kycFailUrl: https://app.eusd.com/#/kycFail
  kycProgressUrl: https://app.eusd.com/
  companyId: 4640948916490241
  openUploadCertificates: false
  duplicateRegisterCheck: false
  kyc3SyncUrl: https://app.eusd.com/#/home?kyc=3
  kyc3AsyncUrl: https://open.eusd.com/api/web/coinface/kyc3async
  kyc3Ocr: true
  kyc3UploadCertificate: true
  kyc3DuplicateCheck: true
  kyc3BlacklistCheck: true
  kyc3AmlCheck: true
  merchantUserKyc3SyncUrl: https://app.eusd.com/#/home?kyc=3
  merchantUserKyc3AsyncUrl: https://open.eusd.com/api/open/coinface/merchantuserkyc3async

telegram:
  botToken: 7538518308:AAFvSU5buG1PKeA3Qkc9R49IsjveN1MafK8
  systemChatId: -1002845569473
  notifyUrl: https://api.telegram.org/bot

chippay:
  baseUrl: https://open-v2.chippay.com/cola
  companyId: 4621568441303041
  publicKey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FERHZINWViY283aCtlZk1HMGp3bHg2ZmdadFJZRm1FNFkwUGw2ZGhaNDVXeTBFRE5vUkZMSlZSbk9VY1MzMzZTeXdGUWdpdUh1U1hMc2FEazMxSzNpZklscFI5U21XbysyUzBVdTY5SlBXUG1QcUY5MVM0UlQvenpaeERLSVBCK0RmWmlJb09oVmt3anU4OHE5RzBFQ2xqanVncjY3eVhZOTZ6TVc2TmQ0cURRSURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
  privateKey: {{CP_PRIVATE_KEY}}
  callbackUrl: https://open.eusd.com/api/open/chippay/express/webhook
  callbackPublicKey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDUFYyODRzOXlkT09aR0NVRkl3MS8wZDJtdApDMlhYOFk2b0ZWWXRCcWhubzVoaEk5cXpVT1orVTJSYXFmdThKQWNieHFYYVZYN01VanhsU1dTSE9KNVgyeWlRCjVHc05nTnZwVEtsT252MzdpQy9pSmRhamFxenl4QzFtRGZXK004WDZJUXNXeXZvUmtOWjhWOFdmbUNQdEZMN3YKaUdQYkU5WEtaZlpBcFpSZ1h3SURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==

topUp:
  previewExpireSeconds: 900 #sec

topDown:
  previewExpireSeconds: 900 #sec

exchange:
  previewExpireSeconds: 900 #sec

transfer:
  previewExpireSeconds: 900 #sec

cardToCard:
  previewExpireSeconds: 900 #sec

withdraw:
  checkIntervalSeconds: 60 #sec
  warnCriteriaSeconds: 300 #sec

merchant:
  apiKeyLength: 32
  rsaKeySize: 1024
  cardCategoryId: 301
  batchQueryBillSize: 1000
  batchQueryUserSize: 100
  billCacheExpiryMinutes: 30

manual:
  lockSeconds: 60 #sec

appStore:
  issuerId: 8652d78c-d962-4625-93a7-81209b547a49
  kid: 6GU9SF6Y4M
  privateKey: {{APP_STORE_PRIVATE_KEY}} 
  bundleID: com.eusd.eusdapp
  sandbox: false

websocket:
  bucketSize: 4
  writeWaitMs: 5000
  pongWaitMs: 60000
  pingPeriodMs: 10000
  maxMsgSize: 1048576
  readBufferSize: 1024
  writeBufferSize: 1024
  broadcastSize: 128

firebase:
  jsonFile: |
    {
      "type": "service_account",
      "project_id": "eusd-app",
      "private_key_id": "77c4235b4e63b55d12fec22cd2f1da7622226a36",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDaAhYB/0ZNrp/J\nyBfQcLCGqT0Utz1VdatyJgRED+SYnQBfkjRPEeeODoxkPmg1KkHx8YcDbOAHkVV4\nMY7ww/LM+aKHXGi8vCe4Nq0EO+Er6IT0buY8df/MTVh3IPxnQAHX+BiBZvh9ppz2\nFIeHBNjouvMMQ+ixGQFNRf9LxVaZ09qGNOJi6WNfSSsbVa1GNN5rYYGJbv7JgAyZ\nqEHbfRYAhT4olRLFBTDBUqX4zZKpMeme6z3B/9jcLDRUmvNmJ/PQwqRD3G7g12Dw\nV0mdEDgJ7PdoV0UeEtr9LbzlcSf8TH/WrFQireR+CqQXaTxuk2kZ3Z66YjeFpG5+\n0LJCOVP3AgMBAAECggEAA4T5GfsnBWYGSlmimMjY8LOWutjicpi9tdALTZX8GMKg\nGOrhUU12sYJmnc+sGv+dpOxDQ7jkPPsJqDEUn6pqJwj4qLrDLhjTg1POozzcO7s7\nOj74FI3LHV86SGIN8RTFctkcfCpPZKfl7MsUDQf1AHzUI6SNAx7mOHsizfRXm5Aa\nVv6PUUNbMUnLekB5VWgkFy009jpEG9zaKP2cJYepmanzxHqrFILmcCsH3ivNlmi+\niIHl7/PfkKGebJqSzh1f+8gFCZMT175Uyp6EHik5tY3/QmfC9GYcWbRktLzBJqaw\nIF9em/ko1/PYPP+GSuTIKgPpC7Mjvpt4xID3FlA0sQKBgQDbaD8lurx6Veq+N/df\nuWuQ8ok1OIJdxEipgFTfMpd9tuzZfhaUQHpPw0uzWGJlwIGyHxoHPcgcwyUwqq0F\nEKv54/2lC8wONh78H9B+Jqoq8yLqPx32AFptdOoLje0d7I1V7MVqwQW2zK+ftdge\nct+K9yQZPRRAlyNlc7FzMtpsDQKBgQD+Xhrsm+oEdvuElus6OLWVQlSil8PltSKS\nj/HXAvRSw6eIX2EUvDMOtRT5HGKF5qweCC6BE/3HlwwVCA4Ddd05CknhUDuWqymB\nIvZnm9H/1YeORgNDdoGP76VY/h5wzITnW795wJBEpwbETFTMGPZk9bN1IVAI5fuf\nEXpTE2nLEwKBgQDI5n6T5JX6irtEa+imDRlSgtJiGhk9FKLYGfsc2K1gXmQnjk3M\nd/HHIXMqiC6pLwlS+SmTId4fgAyIsG93KNngGgRB4Th6dtIOWG9HY84DP9hjl2Gu\nxIoImbpI1C8fbF/KIuBtrMq3pFrXqeF3mAXasAus1IG71uiBV9tPOWxI7QKBgF9A\nI/roI4iKeYLb9Le3lp+O2ByOkifJXWnehyQJki4P4ANcHAFkvAXM306tR2N2zors\na2Wgc86yjC6v9ndrQmziomnB3p57963IxtZjbg7MCdfH9d7kWH3qslMRzZpVq4rr\nO1c/OYbLuOf24WYQDuwdaZb543uBi2i0ZccIJPyLAoGAI3JMOKaWmIncHM3UstMz\nBvFBCvW9oOjoVWPsnlgN8BrzSmlDpqcFN2Yc4sYApuj02EyC1Gt7RnqrUSSERArQ\nnEhSWHoBAU2rvoWamos9Li8aViQFXpKlZTeY/Md64D3xq6HecyKjgwJ2J/Difrsn\nrlRqN9nwrmz+MWCuNxZ/L2Q=\n-----END PRIVATE KEY-----\n",
      "client_email": "firebase-adminsdk-jbz2v@eusd-app.iam.gserviceaccount.com",
      "client_id": "110445895624495914154",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-jbz2v%40eusd-app.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }

s3:
  accessKey: AKIAV7WCPMSRGVLOBNTS
  secretKey: {{S3_SECRET_KEY}}
  region: ap-east-1
  bucketName: euinside
  baseDirectory: files

point:
  defaultExpiryMonths: 12

changelly:
  baseUrl: https://fiat-api.changelly.com/
  apiKey: {{CHANGELLY_API_KEY}} 
  privateKey: {{CHANGELLY_PRIVATE_KEY}} 
  publicKey: 'LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQWxIVUdmdGVyQU1vNWpray92L0phOUhFMzJOZnNrZEdvM2YvUlR6cVQwOWFlNnM3MEZ6M2wKRGRBSXJucjJhRENvK3NtaGRTenBCMzh3eGdoandOaWVySjZ6YU53MDRSMkJ0ZGgrRk5CR2U1MHBsM2habmJSTQpNS3pBcWlDeStGQjlnb3djVzkzYjA2N3B3NytxYmN3ZnpRdTYrWnE4Wk02ejdYUWJTamFoeXVyUmRLWlRLVGFJClI4Z1ZHUmN6Sng1M3g0SkNIMytOOExybDRyTStQdzQybEtMS2V5Q1I2czZVOExTalhmZm8xQno2aGVwMnlvOCsKVGRFSTRrc3RnOHZmODN6dmw0YzY0NmJKM0htZ2xGZk1wNjRyRzVyRWNSa3E4ZVAyVXU0ZTNjaUk5NGhoUkJTNAo1UXRtRTBIVVZQN1BXV0NSK211ai90QXpIK2dzN0JQVitRSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K'

financial:
  snapshotBatchSize: 3000
  userBatchSize: 1000

whale:
  baseUrl: https://www.whalecard.ai/
  coinAppId: {{WHALE_COIN_APP_ID}}
  aesKey: {{WHALE_AES_KEY}}
  aesIv: {{WHALE_AES_IV}}
  activationDeposit: 2
  activationFee: 1
  transferLockMicroseconds: 100000000 #usec
  transferLockWaitMicroseconds: 60000000 #usec
  adjustBalanceFee: 1
  checkAdjustOrderFromMinutes: 480
  checkAdjustOrderToMinutes: 5
  pollingBalanceAttempts: 5
  pollingBalanceIntervalMilliseconds: 1000 #msec


paycrypto:
  baseUrl: https://api.paycrypto.com
  apiKey: {{PAYCRYPTO_APP_KEY}}
  apiSecret: {{PAYCRYPTO_APP_SECRET}}
  apiPassphrase: {{PAYCRYPTO_APP_PASSPHRASE}}
  activationDeposit: 0.01
  privateKey: {{PAYCRYPTO_PRIVATE_KEY}}
  publicKey: {{PAYCRYPTO_PUBLIC_KEY}}

binance:
  host: https://bpay.binanceapi.com
  apiKey: {{BINANCEPAY_API_KEY}}
  secretKey: {{BINANCEPAY_SECRET_KEY}}
  orderExpireTime: 15
  webhook: "https://www.eusd.com/api/open/webhook/binancepay/notify"

etherfi:
  baseUrl: https://www.ether.fi/app/cash/api
  accountId: a75cb37a-e9a0-40e4-a5fd-063ec809d6a9
  safeId: eec62946-eb01-455c-b442-87da464abbb1
  legalMailFrom: ether.fi
  usdtToken: 0xf55BEC9cafDbE8730f096Aa55dad6D22d44099Df
  usdcToken: 0x06eFdBFf2a14a7c8E15944D1F4A48F9F95F663A4

scroll:
  scheme: wss
  baseUrl: scroll-mainnet.infura.io
  path: /ws/v3/
  apikey: {{SCROLL_API_KEY}}
  targets:
    - currency: USDT
      address: 0x640921ecd16b2A2aF238562c63443C5F7B74396A
#    - currency: SCR
#      address: 0x640921ecd16b2A2aF238562c63443C5F7B74396A
#    - currency: USDC
#      address: 0x640921ecd16b2A2aF238562c63443C5F7B74396A


