services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: easy_vault_api
    environment:
      CONFIG_FILE: /app/.env
    # volumes:
    #   - ./.env:/app/.env.docker:ro
    ports:
      - "8082:8081"
      - "9444:9443"
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: easy_vault_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: easy_vault
    ports:
      - "3312:3306"
    # volumes:
    #   - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: easy_vault_redis
    command: ["redis-server", "--requirepass", "123456"]
    ports:
      - "6380:6379"
    # volumes:
    #   - redis_data:/data
    restart: unless-stopped

# volumes:
#   mysql_data:
#   redis_data:
