// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/test/account/addAssets": {
            "post": {
                "tags": [
                    "test/account"
                ],
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.AddAssetsForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "X-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {}
            }
        },
        "/test/test/forTest": {
            "post": {
                "tags": [
                    "test/test"
                ],
                "responses": {}
            }
        },
        "/web/exchange/confirm": {
            "post": {
                "tags": [
                    "web/exchange"
                ],
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.ExchangeConfirmForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "X-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "0": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/entities.ExchangeConfirmVO"
                        }
                    }
                }
            }
        },
        "/web/exchange/preview": {
            "get": {
                "tags": [
                    "web/exchange"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "From wallet id",
                        "name": "fromWalletId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "To currency",
                        "name": "toCurrency",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "From amount (decimal)",
                        "name": "fromAmount",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "X-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "0": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/entities.ExchangePreviewVO"
                        }
                    }
                }
            }
        },
        "/web/order/transactions/page": {
            "get": {
                "tags": [
                    "web/order"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Wallet ID",
                        "name": "walletID",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Current page",
                        "name": "current",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "X-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {}
            }
        },
        "/web/quote/exchangeRate/:quote/:base": {
            "get": {
                "tags": [
                    "web/quote"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quote currency",
                        "name": "quote",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Base currency",
                        "name": "base",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Purpose",
                        "name": "purpose",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "X-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "0": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/entities.ExchangeRateVO"
                        }
                    }
                }
            }
        },
        "/web/system/parameters": {
            "get": {
                "description": "List all system parameters.",
                "tags": [
                    "web/system"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Parameter key",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "X-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "0": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/entities.ListSystemParametersVO"
                        }
                    }
                }
            }
        },
        "/web/transfer/confirm": {
            "post": {
                "tags": [
                    "web/transfer"
                ],
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.TransferConfirmForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "X-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "0": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/entities.TransferConfirmVO"
                        }
                    }
                }
            }
        },
        "/web/transfer/preview": {
            "get": {
                "tags": [
                    "web/transfer"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "From wallet id",
                        "name": "fromWalletId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "to User id",
                        "name": "toUserId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "to email",
                        "name": "toEmail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "From amount (decimal)",
                        "name": "fromAmount",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "X-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "0": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/entities.ExchangePreviewVO"
                        }
                    }
                }
            }
        },
        "/web/user/:id": {
            "get": {
                "tags": [
                    "web/user"
                ],
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.GetInfoForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "X-Token",
                        "name": "X-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/entities.GetInfoVO"
                        }
                    }
                }
            }
        },
        "/web/user/loginOrRegister": {
            "post": {
                "tags": [
                    "web/user"
                ],
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.LoginOrCreateForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "回傳User token",
                        "name": "X-Token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "回傳失效時間",
                        "name": "X-ExpiredTs",
                        "in": "header"
                    }
                ],
                "responses": {
                    "0": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/entities.LoginOrCreateVO"
                        }
                    }
                }
            }
        },
        "/web/user/logout": {
            "post": {
                "tags": [
                    "web/user"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Token",
                        "name": "X-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/web/wallet": {
            "get": {
                "tags": [
                    "web/wallet"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "X-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {}
            }
        },
        "/web/wallet/apply": {
            "post": {
                "tags": [
                    "web/wallet"
                ],
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreateWalletForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "X-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {}
            }
        },
        "/web/wallet/category": {
            "get": {
                "tags": [
                    "web/wallet"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "X-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "0": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/entities.CategoryVO"
                        }
                    }
                }
            }
        },
        "/web/websocket/connect/:token": {
            "get": {
                "tags": [
                    "web/websocket"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "X-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "common.NationCode": {
            "type": "string",
            "enum": [
                "USA",
                "JPN",
                "AUT",
                "BEL",
                "BGR",
                "CYP",
                "CZE",
                "DEU",
                "DNK",
                "ESP",
                "EST",
                "FIN",
                "FRA",
                "GRC",
                "HUN",
                "IRL",
                "ITA",
                "LAT",
                "LIT",
                "LUX",
                "MLT",
                "NLD",
                "POL",
                "PRT",
                "ROU",
                "SVK",
                "SVN",
                "SWE",
                "GBR",
                "CHN",
                "CAN",
                "AUS",
                "CHE",
                "HKG",
                "NZL",
                "MEX",
                "SGP",
                "NOR",
                "KOR",
                "TUR",
                "IND",
                "BRA",
                "ZAF",
                "RUS",
                "TWN",
                "ISR",
                "ARE",
                "ARG",
                "MYS",
                "THA",
                "SAU",
                "IDN",
                "PAK",
                "NGA",
                "EGY",
                "VNM",
                "PHL",
                "COL",
                "CHL",
                "PER",
                "DZA",
                "MAR",
                "KEN",
                "UKR",
                "AFG",
                "ETH",
                "COD",
                "TZA",
                "UZB",
                "ALA",
                "ALB",
                "ASM",
                "AND",
                "AGO",
                "AIA",
                "ATA",
                "ATG",
                "ARM",
                "ABW",
                "AZE",
                "BHS",
                "BHR",
                "BGD",
                "BRB",
                "BLR",
                "BLZ",
                "BEN",
                "BMU",
                "BTN",
                "BOL",
                "BES",
                "BIH",
                "BWA",
                "BVT",
                "IOT",
                "BRN",
                "BFA",
                "BDI",
                "CPV",
                "KHM",
                "CMR",
                "CYM",
                "CAF",
                "TCD",
                "CXR",
                "CCK",
                "COM",
                "COG",
                "COK",
                "CRI",
                "CIV",
                "HRV",
                "CUB",
                "CUW",
                "DJI",
                "DMA",
                "DOM",
                "ECU",
                "SLV",
                "GNQ",
                "ERI",
                "SWZ",
                "FLK",
                "FRO",
                "FJI",
                "GUF",
                "PYF",
                "ATF",
                "GAB",
                "GMB",
                "GEO",
                "GHA",
                "GIB",
                "GRL",
                "GRD",
                "GLP",
                "GUM",
                "GTM",
                "GGY",
                "GIN",
                "GNB",
                "GUY",
                "HTI",
                "HMD",
                "VAT",
                "HND",
                "ISL",
                "IRN",
                "IRQ",
                "IMN",
                "JAM",
                "JEY",
                "JOR",
                "KAZ",
                "KIR",
                "PRK",
                "KWT",
                "KGZ",
                "LAO",
                "LVA",
                "LBN",
                "LSO",
                "LBR",
                "LBY",
                "LIE",
                "LTU",
                "MAC",
                "MDG",
                "MWI",
                "MDV",
                "MLI",
                "MHL",
                "MTQ",
                "MRT",
                "MUS",
                "MYT",
                "FSM",
                "MDA",
                "MCO",
                "MNG",
                "MNE",
                "MSR",
                "MOZ",
                "MMR",
                "NAM",
                "NRU",
                "NPL",
                "NCL",
                "NIC",
                "NER",
                "NIU",
                "NFK",
                "MKD",
                "MNP",
                "OMN",
                "PLW",
                "PSE",
                "PAN",
                "PNG",
                "PRY",
                "PCN",
                "PRI",
                "QAT",
                "REU",
                "RWA",
                "BLM",
                "SHN",
                "KNA",
                "LCA",
                "MAF",
                "SPM",
                "VCT",
                "WSM",
                "SMR",
                "STP",
                "SEN",
                "SRB",
                "SYC",
                "SLE",
                "SXM",
                "SLB",
                "SOM",
                "SGS",
                "SSD",
                "LKA",
                "SDN",
                "SUR",
                "SJM",
                "SYR",
                "TJK",
                "TLS",
                "TGO",
                "TKL",
                "TON",
                "TTO",
                "TUN",
                "TKM",
                "TCA",
                "TUV",
                "UGA",
                "UMI",
                "URY",
                "VUT",
                "VEN",
                "VGB",
                "VIR",
                "WLF",
                "ESH",
                "YEM",
                "ZMB",
                "ZWE"
            ],
            "x-enum-comments": {
                "NATION_CODE_ABW": "Aruba",
                "NATION_CODE_AFG": "阿富汗 (Afghanistan)",
                "NATION_CODE_AGO": "Angola",
                "NATION_CODE_AIA": "Anguilla",
                "NATION_CODE_ALA": "Åland Islands",
                "NATION_CODE_ALB": "Albania",
                "NATION_CODE_AND": "Andorra",
                "NATION_CODE_ARM": "Armenia",
                "NATION_CODE_ASM": "American Samoa",
                "NATION_CODE_ATA": "Antarctica",
                "NATION_CODE_ATF": "French Southern Territories",
                "NATION_CODE_ATG": "Antigua and Barbuda",
                "NATION_CODE_AUT": "EU Austria",
                "NATION_CODE_AZE": "Azerbaijan",
                "NATION_CODE_BDI": "Burundi",
                "NATION_CODE_BEL": "EU Belgium",
                "NATION_CODE_BEN": "Benin",
                "NATION_CODE_BES": "Bonaire, Sint Eustatius and Saba",
                "NATION_CODE_BFA": "Burkina Faso",
                "NATION_CODE_BGD": "Bangladesh",
                "NATION_CODE_BGR": "EU Bulgaria",
                "NATION_CODE_BHR": "Bahrain",
                "NATION_CODE_BHS": "Bahamas",
                "NATION_CODE_BIH": "Bosnia and Herzegovina",
                "NATION_CODE_BLM": "Saint Barthélemy",
                "NATION_CODE_BLR": "Belarus",
                "NATION_CODE_BLZ": "Belize",
                "NATION_CODE_BMU": "Bermuda",
                "NATION_CODE_BOL": "Bolivia (Plurinational State of)",
                "NATION_CODE_BRB": "Barbados",
                "NATION_CODE_BRN": "Brunei Darussalam",
                "NATION_CODE_BTN": "Bhutan",
                "NATION_CODE_BVT": "Bouvet Island",
                "NATION_CODE_BWA": "Botswana",
                "NATION_CODE_CAF": "Central African Republic",
                "NATION_CODE_CCK": "Cocos (Keeling) Islands",
                "NATION_CODE_CHL": "智利 (Chile)",
                "NATION_CODE_CIV": "Côte d'Ivoire",
                "NATION_CODE_CMR": "Cameroon",
                "NATION_CODE_COD": "剛果民主共和國 (Democratic Republic of the Congo)",
                "NATION_CODE_COG": "Congo",
                "NATION_CODE_COK": "Cook Islands",
                "NATION_CODE_COL": "哥倫比亞 (Colombia)",
                "NATION_CODE_COM": "Comoros",
                "NATION_CODE_CPV": "Cabo Verde",
                "NATION_CODE_CRI": "Costa Rica",
                "NATION_CODE_CUB": "Cuba",
                "NATION_CODE_CUW": "Curaçao",
                "NATION_CODE_CXR": "Christmas Island",
                "NATION_CODE_CYM": "Cayman Islands",
                "NATION_CODE_CYP": "EU Cyprus",
                "NATION_CODE_CZE": "EU Czech Republic",
                "NATION_CODE_DEU": "EU Germany",
                "NATION_CODE_DJI": "Djibouti",
                "NATION_CODE_DMA": "Dominica",
                "NATION_CODE_DNK": "EU Denmark",
                "NATION_CODE_DOM": "Dominican Republic",
                "NATION_CODE_DZA": "阿爾及利亞 (Algeria)",
                "NATION_CODE_ECU": "Ecuador",
                "NATION_CODE_EGY": "埃及 (Egypt)",
                "NATION_CODE_ERI": "Eritrea",
                "NATION_CODE_ESH": "Western Sahara",
                "NATION_CODE_ESP": "EU Spain",
                "NATION_CODE_EST": "EU Estonia",
                "NATION_CODE_ETH": "埃塞俄比亞 (Ethiopia)",
                "NATION_CODE_FIN": "EU Finland",
                "NATION_CODE_FJI": "Fiji",
                "NATION_CODE_FLK": "Falkland Islands (Malvinas)",
                "NATION_CODE_FRA": "EU France",
                "NATION_CODE_FRO": "Faroe Islands",
                "NATION_CODE_FSM": "Micronesia (Federated States of)",
                "NATION_CODE_GAB": "Gabon",
                "NATION_CODE_GEO": "Georgia",
                "NATION_CODE_GGY": "Guernsey",
                "NATION_CODE_GHA": "Ghana",
                "NATION_CODE_GIB": "Gibraltar",
                "NATION_CODE_GIN": "Guinea",
                "NATION_CODE_GLP": "Guadeloupe",
                "NATION_CODE_GMB": "Gambia",
                "NATION_CODE_GNB": "Guinea-Bissau",
                "NATION_CODE_GNQ": "Equatorial Guinea",
                "NATION_CODE_GRC": "EU Greece",
                "NATION_CODE_GRD": "Grenada",
                "NATION_CODE_GRL": "Greenland",
                "NATION_CODE_GTM": "Guatemala",
                "NATION_CODE_GUF": "French Guiana",
                "NATION_CODE_GUM": "Guam",
                "NATION_CODE_GUY": "Guyana",
                "NATION_CODE_HMD": "Heard Island and McDonald Islands",
                "NATION_CODE_HND": "Honduras",
                "NATION_CODE_HRV": "Croatia",
                "NATION_CODE_HTI": "Haiti",
                "NATION_CODE_HUN": "EU Hungary",
                "NATION_CODE_IDN": "印尼 (Indonesia)",
                "NATION_CODE_IMN": "Isle of Man",
                "NATION_CODE_IOT": "British Indian Ocean Territory",
                "NATION_CODE_IRL": "EU Ireland",
                "NATION_CODE_IRN": "Iran (Islamic Republic of)",
                "NATION_CODE_IRQ": "Iraq",
                "NATION_CODE_ISL": "Iceland",
                "NATION_CODE_ITA": "EU Italy",
                "NATION_CODE_JAM": "Jamaica",
                "NATION_CODE_JEY": "Jersey",
                "NATION_CODE_JOR": "Jordan",
                "NATION_CODE_KAZ": "Kazakhstan",
                "NATION_CODE_KEN": "肯亞 (Kenya)",
                "NATION_CODE_KGZ": "Kyrgyzstan",
                "NATION_CODE_KHM": "Cambodia",
                "NATION_CODE_KIR": "Kiribati",
                "NATION_CODE_KNA": "Saint Kitts and Nevis",
                "NATION_CODE_KWT": "Kuwait",
                "NATION_CODE_LAO": "Lao People's Democratic Republic",
                "NATION_CODE_LAT": "EU Latvia",
                "NATION_CODE_LBN": "Lebanon",
                "NATION_CODE_LBR": "Liberia",
                "NATION_CODE_LBY": "Libya",
                "NATION_CODE_LCA": "Saint Lucia",
                "NATION_CODE_LIE": "Liechtenstein",
                "NATION_CODE_LIT": "EU Lithuania",
                "NATION_CODE_LKA": "Sri Lanka",
                "NATION_CODE_LSO": "Lesotho",
                "NATION_CODE_LTU": "Lithuania",
                "NATION_CODE_LUX": "EU Luxembourg",
                "NATION_CODE_LVA": "Latvia",
                "NATION_CODE_MAC": "Macao",
                "NATION_CODE_MAF": "Saint Martin (French part)",
                "NATION_CODE_MAR": "摩洛哥 (Morocco)",
                "NATION_CODE_MCO": "Monaco",
                "NATION_CODE_MDA": "Moldova, Republic of",
                "NATION_CODE_MDG": "Madagascar",
                "NATION_CODE_MDV": "Maldives",
                "NATION_CODE_MHL": "Marshall Islands",
                "NATION_CODE_MKD": "North Macedonia",
                "NATION_CODE_MLI": "Mali",
                "NATION_CODE_MLT": "EU Malta",
                "NATION_CODE_MMR": "Myanmar",
                "NATION_CODE_MNE": "Montenegro",
                "NATION_CODE_MNG": "Mongolia",
                "NATION_CODE_MNP": "Northern Mariana Islands",
                "NATION_CODE_MOZ": "Mozambique",
                "NATION_CODE_MRT": "Mauritania",
                "NATION_CODE_MSR": "Montserrat",
                "NATION_CODE_MTQ": "Martinique",
                "NATION_CODE_MUS": "Mauritius",
                "NATION_CODE_MWI": "Malawi",
                "NATION_CODE_MYT": "Mayotte",
                "NATION_CODE_NAM": "Namibia",
                "NATION_CODE_NCL": "New Caledonia",
                "NATION_CODE_NER": "Niger",
                "NATION_CODE_NFK": "Norfolk Island",
                "NATION_CODE_NGA": "奈及利亞 (Nigeria)",
                "NATION_CODE_NIC": "Nicaragua",
                "NATION_CODE_NIU": "Niue",
                "NATION_CODE_NLD": "EU Netherlands",
                "NATION_CODE_NPL": "Nepal",
                "NATION_CODE_NRU": "Nauru",
                "NATION_CODE_OMN": "Oman",
                "NATION_CODE_PAK": "巴基斯坦 (Pakistan)",
                "NATION_CODE_PAN": "Panama",
                "NATION_CODE_PCN": "Pitcairn",
                "NATION_CODE_PER": "秘魯 (Peru)",
                "NATION_CODE_PHL": "菲律賓 (Philippines)",
                "NATION_CODE_PLW": "Palau",
                "NATION_CODE_PNG": "Papua New Guinea",
                "NATION_CODE_POL": "EU Poland",
                "NATION_CODE_PRI": "Puerto Rico",
                "NATION_CODE_PRK": "Korea (Democratic People's Republic of)",
                "NATION_CODE_PRT": "EU Portugal",
                "NATION_CODE_PRY": "Paraguay",
                "NATION_CODE_PSE": "Palestine, State of",
                "NATION_CODE_PYF": "French Polynesia",
                "NATION_CODE_QAT": "Qatar",
                "NATION_CODE_REU": "Réunion",
                "NATION_CODE_ROU": "EU Romania",
                "NATION_CODE_RWA": "Rwanda",
                "NATION_CODE_SDN": "Sudan",
                "NATION_CODE_SEN": "Senegal",
                "NATION_CODE_SGS": "South Georgia and the South Sandwich Islands",
                "NATION_CODE_SHN": "Saint Helena, Ascension and Tristan da Cunha",
                "NATION_CODE_SJM": "Svalbard and Jan Mayen",
                "NATION_CODE_SLB": "Solomon Islands",
                "NATION_CODE_SLE": "Sierra Leone",
                "NATION_CODE_SLV": "El Salvador",
                "NATION_CODE_SMR": "San Marino",
                "NATION_CODE_SOM": "Somalia",
                "NATION_CODE_SPM": "Saint Pierre and Miquelon",
                "NATION_CODE_SRB": "Serbia",
                "NATION_CODE_SSD": "South Sudan",
                "NATION_CODE_STP": "Sao Tome and Principe",
                "NATION_CODE_SUR": "Suriname",
                "NATION_CODE_SVK": "EU Slovakia",
                "NATION_CODE_SVN": "EU Slovenia",
                "NATION_CODE_SWE": "EU Sweden",
                "NATION_CODE_SWZ": "Eswatini",
                "NATION_CODE_SXM": "Sint Maarten (Dutch part)",
                "NATION_CODE_SYC": "Seychelles",
                "NATION_CODE_SYR": "Syrian Arab Republic",
                "NATION_CODE_TCA": "Turks and Caicos Islands",
                "NATION_CODE_TCD": "Chad",
                "NATION_CODE_TGO": "Togo",
                "NATION_CODE_TJK": "Tajikistan",
                "NATION_CODE_TKL": "Tokelau",
                "NATION_CODE_TKM": "Turkmenistan",
                "NATION_CODE_TLS": "Timor-Leste",
                "NATION_CODE_TON": "Tonga",
                "NATION_CODE_TTO": "Trinidad and Tobago",
                "NATION_CODE_TUN": "Tunisia",
                "NATION_CODE_TUV": "Tuvalu",
                "NATION_CODE_TZA": "坦尚尼亞 (Tanzania)",
                "NATION_CODE_UGA": "Uganda",
                "NATION_CODE_UKR": "烏克蘭 (Ukraine)",
                "NATION_CODE_UMI": "United States Minor Outlying Islands",
                "NATION_CODE_URY": "Uruguay",
                "NATION_CODE_UZB": "烏茲別克 (Uzbekistan)",
                "NATION_CODE_VAT": "Holy See",
                "NATION_CODE_VCT": "Saint Vincent and the Grenadines",
                "NATION_CODE_VEN": "Venezuela (Bolivarian Republic of)",
                "NATION_CODE_VGB": "Virgin Islands (British)",
                "NATION_CODE_VIR": "Virgin Islands (U.S.)",
                "NATION_CODE_VNM": "越南 (Vietnam)",
                "NATION_CODE_VUT": "Vanuatu",
                "NATION_CODE_WLF": "Wallis and Futuna",
                "NATION_CODE_WSM": "Samoa",
                "NATION_CODE_YEM": "Yemen",
                "NATION_CODE_ZMB": "Zambia",
                "NATION_CODE_ZWE": "Zimbabwe"
            },
            "x-enum-descriptions": [
                "",
                "",
                "EU Austria",
                "EU Belgium",
                "EU Bulgaria",
                "EU Cyprus",
                "EU Czech Republic",
                "EU Germany",
                "EU Denmark",
                "EU Spain",
                "EU Estonia",
                "EU Finland",
                "EU France",
                "EU Greece",
                "EU Hungary",
                "EU Ireland",
                "EU Italy",
                "EU Latvia",
                "EU Lithuania",
                "EU Luxembourg",
                "EU Malta",
                "EU Netherlands",
                "EU Poland",
                "EU Portugal",
                "EU Romania",
                "EU Slovakia",
                "EU Slovenia",
                "EU Sweden",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "印尼 (Indonesia)",
                "巴基斯坦 (Pakistan)",
                "奈及利亞 (Nigeria)",
                "埃及 (Egypt)",
                "越南 (Vietnam)",
                "菲律賓 (Philippines)",
                "哥倫比亞 (Colombia)",
                "智利 (Chile)",
                "秘魯 (Peru)",
                "阿爾及利亞 (Algeria)",
                "摩洛哥 (Morocco)",
                "肯亞 (Kenya)",
                "烏克蘭 (Ukraine)",
                "阿富汗 (Afghanistan)",
                "埃塞俄比亞 (Ethiopia)",
                "剛果民主共和國 (Democratic Republic of the Congo)",
                "坦尚尼亞 (Tanzania)",
                "烏茲別克 (Uzbekistan)",
                "Åland Islands",
                "Albania",
                "American Samoa",
                "Andorra",
                "Angola",
                "Anguilla",
                "Antarctica",
                "Antigua and Barbuda",
                "Armenia",
                "Aruba",
                "Azerbaijan",
                "Bahamas",
                "Bahrain",
                "Bangladesh",
                "Barbados",
                "Belarus",
                "Belize",
                "Benin",
                "Bermuda",
                "Bhutan",
                "Bolivia (Plurinational State of)",
                "Bonaire, Sint Eustatius and Saba",
                "Bosnia and Herzegovina",
                "Botswana",
                "Bouvet Island",
                "British Indian Ocean Territory",
                "Brunei Darussalam",
                "Burkina Faso",
                "Burundi",
                "Cabo Verde",
                "Cambodia",
                "Cameroon",
                "Cayman Islands",
                "Central African Republic",
                "Chad",
                "Christmas Island",
                "Cocos (Keeling) Islands",
                "Comoros",
                "Congo",
                "Cook Islands",
                "Costa Rica",
                "Côte d'Ivoire",
                "Croatia",
                "Cuba",
                "Curaçao",
                "Djibouti",
                "Dominica",
                "Dominican Republic",
                "Ecuador",
                "El Salvador",
                "Equatorial Guinea",
                "Eritrea",
                "Eswatini",
                "Falkland Islands (Malvinas)",
                "Faroe Islands",
                "Fiji",
                "French Guiana",
                "French Polynesia",
                "French Southern Territories",
                "Gabon",
                "Gambia",
                "Georgia",
                "Ghana",
                "Gibraltar",
                "Greenland",
                "Grenada",
                "Guadeloupe",
                "Guam",
                "Guatemala",
                "Guernsey",
                "Guinea",
                "Guinea-Bissau",
                "Guyana",
                "Haiti",
                "Heard Island and McDonald Islands",
                "Holy See",
                "Honduras",
                "Iceland",
                "Iran (Islamic Republic of)",
                "Iraq",
                "Isle of Man",
                "Jamaica",
                "Jersey",
                "Jordan",
                "Kazakhstan",
                "Kiribati",
                "Korea (Democratic People's Republic of)",
                "Kuwait",
                "Kyrgyzstan",
                "Lao People's Democratic Republic",
                "Latvia",
                "Lebanon",
                "Lesotho",
                "Liberia",
                "Libya",
                "Liechtenstein",
                "Lithuania",
                "Macao",
                "Madagascar",
                "Malawi",
                "Maldives",
                "Mali",
                "Marshall Islands",
                "Martinique",
                "Mauritania",
                "Mauritius",
                "Mayotte",
                "Micronesia (Federated States of)",
                "Moldova, Republic of",
                "Monaco",
                "Mongolia",
                "Montenegro",
                "Montserrat",
                "Mozambique",
                "Myanmar",
                "Namibia",
                "Nauru",
                "Nepal",
                "New Caledonia",
                "Nicaragua",
                "Niger",
                "Niue",
                "Norfolk Island",
                "North Macedonia",
                "Northern Mariana Islands",
                "Oman",
                "Palau",
                "Palestine, State of",
                "Panama",
                "Papua New Guinea",
                "Paraguay",
                "Pitcairn",
                "Puerto Rico",
                "Qatar",
                "Réunion",
                "Rwanda",
                "Saint Barthélemy",
                "Saint Helena, Ascension and Tristan da Cunha",
                "Saint Kitts and Nevis",
                "Saint Lucia",
                "Saint Martin (French part)",
                "Saint Pierre and Miquelon",
                "Saint Vincent and the Grenadines",
                "Samoa",
                "San Marino",
                "Sao Tome and Principe",
                "Senegal",
                "Serbia",
                "Seychelles",
                "Sierra Leone",
                "Sint Maarten (Dutch part)",
                "Solomon Islands",
                "Somalia",
                "South Georgia and the South Sandwich Islands",
                "South Sudan",
                "Sri Lanka",
                "Sudan",
                "Suriname",
                "Svalbard and Jan Mayen",
                "Syrian Arab Republic",
                "Tajikistan",
                "Timor-Leste",
                "Togo",
                "Tokelau",
                "Tonga",
                "Trinidad and Tobago",
                "Tunisia",
                "Turkmenistan",
                "Turks and Caicos Islands",
                "Tuvalu",
                "Uganda",
                "United States Minor Outlying Islands",
                "Uruguay",
                "Vanuatu",
                "Venezuela (Bolivarian Republic of)",
                "Virgin Islands (British)",
                "Virgin Islands (U.S.)",
                "Wallis and Futuna",
                "Western Sahara",
                "Yemen",
                "Zambia",
                "Zimbabwe"
            ],
            "x-enum-varnames": [
                "NATION_CODE_USA",
                "NATION_CODE_JPN",
                "NATION_CODE_AUT",
                "NATION_CODE_BEL",
                "NATION_CODE_BGR",
                "NATION_CODE_CYP",
                "NATION_CODE_CZE",
                "NATION_CODE_DEU",
                "NATION_CODE_DNK",
                "NATION_CODE_ESP",
                "NATION_CODE_EST",
                "NATION_CODE_FIN",
                "NATION_CODE_FRA",
                "NATION_CODE_GRC",
                "NATION_CODE_HUN",
                "NATION_CODE_IRL",
                "NATION_CODE_ITA",
                "NATION_CODE_LAT",
                "NATION_CODE_LIT",
                "NATION_CODE_LUX",
                "NATION_CODE_MLT",
                "NATION_CODE_NLD",
                "NATION_CODE_POL",
                "NATION_CODE_PRT",
                "NATION_CODE_ROU",
                "NATION_CODE_SVK",
                "NATION_CODE_SVN",
                "NATION_CODE_SWE",
                "NATION_CODE_GBR",
                "NATION_CODE_CHN",
                "NATION_CODE_CAN",
                "NATION_CODE_AUS",
                "NATION_CODE_CHE",
                "NATION_CODE_HKG",
                "NATION_CODE_NZL",
                "NATION_CODE_MEX",
                "NATION_CODE_SGP",
                "NATION_CODE_NOR",
                "NATION_CODE_KOR",
                "NATION_CODE_TUR",
                "NATION_CODE_IND",
                "NATION_CODE_BRA",
                "NATION_CODE_ZAF",
                "NATION_CODE_RUS",
                "NATION_CODE_TWN",
                "NATION_CODE_ISR",
                "NATION_CODE_ARE",
                "NATION_CODE_ARG",
                "NATION_CODE_MYS",
                "NATION_CODE_THA",
                "NATION_CODE_SAU",
                "NATION_CODE_IDN",
                "NATION_CODE_PAK",
                "NATION_CODE_NGA",
                "NATION_CODE_EGY",
                "NATION_CODE_VNM",
                "NATION_CODE_PHL",
                "NATION_CODE_COL",
                "NATION_CODE_CHL",
                "NATION_CODE_PER",
                "NATION_CODE_DZA",
                "NATION_CODE_MAR",
                "NATION_CODE_KEN",
                "NATION_CODE_UKR",
                "NATION_CODE_AFG",
                "NATION_CODE_ETH",
                "NATION_CODE_COD",
                "NATION_CODE_TZA",
                "NATION_CODE_UZB",
                "NATION_CODE_ALA",
                "NATION_CODE_ALB",
                "NATION_CODE_ASM",
                "NATION_CODE_AND",
                "NATION_CODE_AGO",
                "NATION_CODE_AIA",
                "NATION_CODE_ATA",
                "NATION_CODE_ATG",
                "NATION_CODE_ARM",
                "NATION_CODE_ABW",
                "NATION_CODE_AZE",
                "NATION_CODE_BHS",
                "NATION_CODE_BHR",
                "NATION_CODE_BGD",
                "NATION_CODE_BRB",
                "NATION_CODE_BLR",
                "NATION_CODE_BLZ",
                "NATION_CODE_BEN",
                "NATION_CODE_BMU",
                "NATION_CODE_BTN",
                "NATION_CODE_BOL",
                "NATION_CODE_BES",
                "NATION_CODE_BIH",
                "NATION_CODE_BWA",
                "NATION_CODE_BVT",
                "NATION_CODE_IOT",
                "NATION_CODE_BRN",
                "NATION_CODE_BFA",
                "NATION_CODE_BDI",
                "NATION_CODE_CPV",
                "NATION_CODE_KHM",
                "NATION_CODE_CMR",
                "NATION_CODE_CYM",
                "NATION_CODE_CAF",
                "NATION_CODE_TCD",
                "NATION_CODE_CXR",
                "NATION_CODE_CCK",
                "NATION_CODE_COM",
                "NATION_CODE_COG",
                "NATION_CODE_COK",
                "NATION_CODE_CRI",
                "NATION_CODE_CIV",
                "NATION_CODE_HRV",
                "NATION_CODE_CUB",
                "NATION_CODE_CUW",
                "NATION_CODE_DJI",
                "NATION_CODE_DMA",
                "NATION_CODE_DOM",
                "NATION_CODE_ECU",
                "NATION_CODE_SLV",
                "NATION_CODE_GNQ",
                "NATION_CODE_ERI",
                "NATION_CODE_SWZ",
                "NATION_CODE_FLK",
                "NATION_CODE_FRO",
                "NATION_CODE_FJI",
                "NATION_CODE_GUF",
                "NATION_CODE_PYF",
                "NATION_CODE_ATF",
                "NATION_CODE_GAB",
                "NATION_CODE_GMB",
                "NATION_CODE_GEO",
                "NATION_CODE_GHA",
                "NATION_CODE_GIB",
                "NATION_CODE_GRL",
                "NATION_CODE_GRD",
                "NATION_CODE_GLP",
                "NATION_CODE_GUM",
                "NATION_CODE_GTM",
                "NATION_CODE_GGY",
                "NATION_CODE_GIN",
                "NATION_CODE_GNB",
                "NATION_CODE_GUY",
                "NATION_CODE_HTI",
                "NATION_CODE_HMD",
                "NATION_CODE_VAT",
                "NATION_CODE_HND",
                "NATION_CODE_ISL",
                "NATION_CODE_IRN",
                "NATION_CODE_IRQ",
                "NATION_CODE_IMN",
                "NATION_CODE_JAM",
                "NATION_CODE_JEY",
                "NATION_CODE_JOR",
                "NATION_CODE_KAZ",
                "NATION_CODE_KIR",
                "NATION_CODE_PRK",
                "NATION_CODE_KWT",
                "NATION_CODE_KGZ",
                "NATION_CODE_LAO",
                "NATION_CODE_LVA",
                "NATION_CODE_LBN",
                "NATION_CODE_LSO",
                "NATION_CODE_LBR",
                "NATION_CODE_LBY",
                "NATION_CODE_LIE",
                "NATION_CODE_LTU",
                "NATION_CODE_MAC",
                "NATION_CODE_MDG",
                "NATION_CODE_MWI",
                "NATION_CODE_MDV",
                "NATION_CODE_MLI",
                "NATION_CODE_MHL",
                "NATION_CODE_MTQ",
                "NATION_CODE_MRT",
                "NATION_CODE_MUS",
                "NATION_CODE_MYT",
                "NATION_CODE_FSM",
                "NATION_CODE_MDA",
                "NATION_CODE_MCO",
                "NATION_CODE_MNG",
                "NATION_CODE_MNE",
                "NATION_CODE_MSR",
                "NATION_CODE_MOZ",
                "NATION_CODE_MMR",
                "NATION_CODE_NAM",
                "NATION_CODE_NRU",
                "NATION_CODE_NPL",
                "NATION_CODE_NCL",
                "NATION_CODE_NIC",
                "NATION_CODE_NER",
                "NATION_CODE_NIU",
                "NATION_CODE_NFK",
                "NATION_CODE_MKD",
                "NATION_CODE_MNP",
                "NATION_CODE_OMN",
                "NATION_CODE_PLW",
                "NATION_CODE_PSE",
                "NATION_CODE_PAN",
                "NATION_CODE_PNG",
                "NATION_CODE_PRY",
                "NATION_CODE_PCN",
                "NATION_CODE_PRI",
                "NATION_CODE_QAT",
                "NATION_CODE_REU",
                "NATION_CODE_RWA",
                "NATION_CODE_BLM",
                "NATION_CODE_SHN",
                "NATION_CODE_KNA",
                "NATION_CODE_LCA",
                "NATION_CODE_MAF",
                "NATION_CODE_SPM",
                "NATION_CODE_VCT",
                "NATION_CODE_WSM",
                "NATION_CODE_SMR",
                "NATION_CODE_STP",
                "NATION_CODE_SEN",
                "NATION_CODE_SRB",
                "NATION_CODE_SYC",
                "NATION_CODE_SLE",
                "NATION_CODE_SXM",
                "NATION_CODE_SLB",
                "NATION_CODE_SOM",
                "NATION_CODE_SGS",
                "NATION_CODE_SSD",
                "NATION_CODE_LKA",
                "NATION_CODE_SDN",
                "NATION_CODE_SUR",
                "NATION_CODE_SJM",
                "NATION_CODE_SYR",
                "NATION_CODE_TJK",
                "NATION_CODE_TLS",
                "NATION_CODE_TGO",
                "NATION_CODE_TKL",
                "NATION_CODE_TON",
                "NATION_CODE_TTO",
                "NATION_CODE_TUN",
                "NATION_CODE_TKM",
                "NATION_CODE_TCA",
                "NATION_CODE_TUV",
                "NATION_CODE_UGA",
                "NATION_CODE_UMI",
                "NATION_CODE_URY",
                "NATION_CODE_VUT",
                "NATION_CODE_VEN",
                "NATION_CODE_VGB",
                "NATION_CODE_VIR",
                "NATION_CODE_WLF",
                "NATION_CODE_ESH",
                "NATION_CODE_YEM",
                "NATION_CODE_ZMB",
                "NATION_CODE_ZWE"
            ]
        },
        "common.Role": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                5,
                6,
                9
            ],
            "x-enum-varnames": [
                "ROLE_GUEST",
                "ROLE_USER",
                "ROLE_ADMIN",
                "ROLE_MERCHANT",
                "ROLE_MERCHANT_ADMIN",
                "ROLE_MERCHANT_USER",
                "ROLE_SYSTEM"
            ]
        },
        "entities.AddAssetsForm": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "assetId": {
                    "type": "string",
                    "example": "0"
                },
                "userId": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "entities.CategoryVO": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "0"
                },
                "currency": {
                    "type": "string"
                },
                "currencyType": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "0"
                },
                "name": {
                    "type": "string"
                },
                "nation": {
                    "type": "string"
                },
                "nationCode": {
                    "$ref": "#/definitions/common.NationCode"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "entities.CreateWalletForm": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "entities.ExchangeConfirmForm": {
            "type": "object",
            "required": [
                "key"
            ],
            "properties": {
                "key": {
                    "type": "string"
                }
            }
        },
        "entities.ExchangeConfirmVO": {
            "type": "object"
        },
        "entities.ExchangePreviewVO": {
            "type": "object",
            "properties": {
                "exchangeFee": {
                    "type": "string"
                },
                "expiredAt": {
                    "type": "string",
                    "example": "0"
                },
                "fromAmount": {
                    "type": "string"
                },
                "fromCardID": {
                    "type": "string",
                    "example": "0"
                },
                "fromCategory": {
                    "type": "string"
                },
                "fromCategoryID": {
                    "type": "string",
                    "example": "0"
                },
                "fromCurrency": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "rate": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ExchangeRateVO"
                    }
                },
                "toAmount": {
                    "type": "string"
                },
                "toCardID": {
                    "type": "string",
                    "example": "0"
                },
                "toCategory": {
                    "type": "string"
                },
                "toCategoryID": {
                    "type": "string",
                    "example": "0"
                },
                "toCurrency": {
                    "type": "string"
                }
            }
        },
        "entities.ExchangeRateVO": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "string"
                },
                "purpose": {
                    "type": "string"
                },
                "quote": {
                    "type": "string"
                },
                "rate": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "entities.GetInfoForm": {
            "type": "object"
        },
        "entities.GetInfoVO": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "0"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "groupIDs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "0"
                },
                "role": {
                    "$ref": "#/definitions/common.Role"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "entities.ListSystemParametersVO": {
            "type": "object",
            "properties": {
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.SystemParameterVO"
                    }
                }
            }
        },
        "entities.LoginOrCreateForm": {
            "type": "object",
            "required": [
                "email",
                "pinCode"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "pinCode": {
                    "type": "string"
                }
            }
        },
        "entities.LoginOrCreateVO": {
            "type": "object",
            "properties": {
                "countryCode": {
                    "description": "可能為空",
                    "type": "integer"
                },
                "createdAt": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "description": "可能為空",
                    "type": "integer"
                },
                "id": {
                    "type": "string",
                    "example": "0"
                },
                "phoneNumber": {
                    "description": "可能為空",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "integer"
                }
            }
        },
        "entities.SystemParameterVO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "0"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "entities.TransferConfirmForm": {
            "type": "object",
            "required": [
                "key",
                "pinCode"
            ],
            "properties": {
                "key": {
                    "type": "string"
                },
                "pinCode": {
                    "type": "string"
                }
            }
        },
        "entities.TransferConfirmVO": {
            "type": "object",
            "properties": {
                "orderNO": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Easy Vault API",
	Description:      "Easy Vault API Server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
